# Generated by Django 5.1.2 on 2024-10-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblCategoriaGasto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblCliente',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblFormaPago',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblProyecto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=10, null=True)),
                ('Nombre', models.CharField(max_length=60, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcliente')),
            ],
        ),
    ]
