# Generated by Django 5.1.2 on 2024-10-29 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblEstatus',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tblproyecto',
            old_name='Nombre',
            new_name='Factura',
        ),
        migrations.RemoveField(
            model_name='tblproyecto',
            name='Folio',
        ),
        migrations.RemoveField(
            model_name='tblproyecto',
            name='IDCliente',
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='Descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='Fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='IDCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcategoriagasto'),
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='IDFormaDePago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblformapago'),
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='Monto',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='Proveedor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='tblAltaProyecto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Folio', models.CharField(max_length=10, null=True)),
                ('Proyecto', models.CharField(max_length=60, null=True)),
                ('Descripcion', models.CharField(max_length=100, null=True)),
                ('FechaInicio', models.DateField(null=True)),
                ('Fechafinal', models.DateField(null=True)),
                ('GastoTotal', models.CharField(max_length=60, null=True)),
                ('IDCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblcliente')),
                ('IDEstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblestatus')),
            ],
        ),
        migrations.AddField(
            model_name='tblproyecto',
            name='IDProyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Aplicacion.tblaltaproyecto'),
        ),
    ]
