# Generated by Django 5.1.2 on 2024-10-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_tblestatus_rename_nombre_tblproyecto_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblaltaproyecto',
            name='Folio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
